name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        nim: ["1.x"]
    name: Nim ${{ matrix.nim }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v2
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
        if: runner.os != 'Windows'
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - name: Run tests
        run: nimble test
